language: python
python:
  - "3.6"
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install libsdl2-dev"
  - "pip install -r requirements/app.txt"
  - "pip install -r requirements/tests.txt"
  - "pip install pyinstaller"
  - "pip install -e ."
script:
  - "py.test"
  - "pyinstaller -y specs/gui.spec"
