environment:
    matrix:
        - PYTHON: "c:\\python36-x64"
platform: x64
install:
    - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
    - "%PYTHON%\\python.exe -m pip install pyinstaller"
    - "%PYTHON%\\python.exe -m pip install -e ."
build_script:
    - '%PYTHON%\\python.exe -c "import sails; print(sails.build_number())" > solar-sails-version.txt'
    - "%PYTHON%\\scripts\\pyinstaller.exe -y specs\\gui.spec"
    # TODO: rename solar-sails to solar-sails-${VERSION} like the linux build does
artifacts:
    - path: dist
