version: 2
jobs:
  linux:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: "sudo apt-get -y install libsdl2-dev | cat"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/base.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/app.txt | cat
            pip install pyinstaller | cat
            pip install -e . | cat
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/base.txt" }}
      - run:
          name: build distributable
          command: |
            . venv/bin/activate
            pyinstaller -y specs/gui.spec
            cd dist
            tar cjvf solar-sails-linux-x64.tar.bz2 solar-sails
      - store_artifacts:
          path: dist/solar-sails-linux-x64.tar.bz2
          destination: solar-sails-linux-x64.tar.bz2
  macos:
    macos:
      xcode: "8.2.1"
    steps:
      - "python --version"
      - "brew --version"
#      - checkout
#      - run: "pip install -r requirements/app.txt"
#      - run: "pip install pyinstaller"
#      - run: "pip install -e ."
#      - run: "pyinstaller -y specs/gui.spec"
workflows:
  version: 2
  everything:
    jobs:
      - linux
      - macos
