version: 2
jobs:
  linux:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/base.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/app.txt
            pip install pyinstaller
            pip install -e .
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/base.txt" }}
      - run:
          name: build distributable
          command: |
            . venv/bin/activate
            pyinstaller -y specs/gui.spec
      - store_artifacts:
          path: dist
          destination: dist
  macos:
    macos:
      xcode: "8.2.1"
    steps:
      - "python --version"
      - "brew --version"
#      - checkout
#      - run: "pip install -r requirements/app.txt"
#      - run: "pip install pyinstaller"
#      - run: "pip install -e ."
#      - run: "pyinstaller -y specs/gui.spec"
workflows:
  version: 2
  everything:
    jobs:
      - linux
      - macos
